site_name: iceoryx.io
site_url: https://iceoryx.io
repo_url: https://github.com/eclipse/iceoryx
docs_dir: doc/website/
remote_branch: main
markdown_extensions:
  - meta
  - markdown_include.include:
      base_path: doc
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
plugins:
  - awesome-pages
  - search
theme:
  name: 'material'
extra:
  version:
    provider: mike
